package DataStructuresAndAlgorithms.Queue.QueueArray

fun main(args: Array<String>) {
    val arrayQueue= QueueArray(5)
    arrayQueue.inqueue(1)
    arrayQueue.inqueue(2)
    arrayQueue.inqueue(3)
    arrayQueue.inqueue(4)
    arrayQueue.inqueue(5)
    println("Before deleting")
    arrayQueue.displayAllItems()
    println("After deleting")
    arrayQueue.dequeue()
    arrayQueue.dequeue()
    arrayQueue.dequeue()
    arrayQueue.dequeue()
    arrayQueue.displayAllItems()
   /* arrayQueue.dequeue()
    //arrayQueue.dequeue()
    println("second adding")
    arrayQueue.inqueue(54)
    arrayQueue.inqueue(540)
    arrayQueue.inqueue(5400)
    arrayQueue.inqueue(54000)
    arrayQueue.inqueue(540000)
    arrayQueue.inqueue(540000000000)
    arrayQueue.displayAllItems()
    println("after second adding")
    arrayQueue.dequeue()
    arrayQueue.dequeue()
    arrayQueue.dequeue()
    arrayQueue.dequeue()
    arrayQueue.dequeue()
    arrayQueue.displayAllItems()
    println("after thid adding")
    arrayQueue.inqueue(9999999999999999)
    arrayQueue.displayAllItems()
   // arrayQueue.inqueue(54)
   // println("After adding new one")
   // arrayQueue.inqueue(6)
    //arrayQueue.displayAllItems()*/

}